name: CD

on:
  release:
    types: [created]
  workflow_run:
    workflows: [ 'Test' ]
    types:
      - completed

jobs:
  pypi:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Poetry
        run: |
          python -m pip install poetry
      - name: Deploy to PyPI
        run: poetry publish --build -u Rhinik -p ${{ secrets.PYPI_PASSWORD }}

