name: CD

on:
  release:
    # Only use the types keyword to narrow down the activity types that will trigger your workflow.
    types: [created]

jobs:
  pypi:
    name: Deploy to PyPI
    needs: coveralls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup Poetry
        run: |
          python -m pip install poetry
      - name: Deploy to PyPI
        run: poetry publish --build -u Rhinik -p ${{ secrets.PYPI_PASSWORD }}

