name: CI

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    name: Run unit-tests
    strategy:
      matrix:
        python-version: [ 3.8, 3.9, "3.10" ]
        platform: ["ubuntu-latest", "macos-11", "windows-2022"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: Installing th current project in dev mode
        run: |
          python -m pip install poetry
          make install-dev
      - name: Run Unit-Tests
        run: make test-ci
      - name: Upload coverage data to coveralls.io
        run: poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: tests
    runs-on: ubuntu-latest
    container: python:3-slim
    steps:
      - name: Finished
        run: |
          pip3 install --upgrade coveralls
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
