name: CI

on:
  push:
    branches:
      - "*"

jobs:
  static_checker:
    runs-on: ubuntu-20.04
    name: Run static analizer
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Installing the current project in dev mode
        run: |
          python -m pip install poetry
          make install-check
      - name: Run mypy
        run: make check

  tests:
    name: Run unit-tests
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "pypy-3.8", "pypy-3.7"]
        platform: ["ubuntu-latest", "macos-11", "windows-2019"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Installing the current project in dev mode
        run: |
          python -m pip install poetry
          make install-test
      - name: Run Unit-Tests
        run: make test-ci
      - name: Upload coverage data to coveralls.io
        run: poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true

  coveralls:
    name: Indicate completion to coveralls.io
    needs: tests
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: Finished
        run: |
          python -m pip install poetry
          make install-test
          coveralls --service=github --finish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
