name: Tests

on:
  push:
    branches:
    - main
    - dev

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.8, 3.9, "3.10" ]

    steps:
      - uses: actions/checkout@v2
      - name: Installing
        run: |
          python -m pip install poetry
          make install-dev
      - name: Run Tests
        run: make test
      - name: Report coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
